### ISSUE TITLE
Support for Unsigned Integer values

### ISSUE THREAD

**Issue by orchestr7** [orchestr7/ktoml#173]
Would you mind elaborating on why unsigneds can't be supported?

I'd recommend making a new GitHub issue 'support unsigned ints' (I could make the issue if you like) and adding the link in the source code, then it's easier to track and follow progress.

_Originally posted by @aSemy in https://github.com/akuleshov7/ktoml/pull/171#discussion_r1058245318_

**Comment by akuleshov7** [comment]
```
    @Serializable
    data class UnsingedIntegers(
        val s: UInt,
        val b: UByte,
        val i: UInt,
        val l: ULong,
    )

      var testUnsigned = """
              s = 5
              b = 5
              i = 5
              l = 5
      """.trimIndent()
      println(Toml.decodeFromString<UnsingedIntegers>(testUnsigned))
```

Will cause error:
```
Index -1 out of bounds for length 4
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.akuleshov7.ktoml.decoders.TomlMainDecoder.getCurrentNode(TomlMainDecoder.kt:81)
```

**Comment by aSemy** [comment]
I think that `UInt.MAX_VALUE` is `-1`, so the current way of validating won't work for unsigned nums.

I'd prefer refracting the logic to match how KsX JSON does it https://github.com/akuleshov7/ktoml/pull/171#discussion_r1058259095

**Comment by akuleshov7** [comment]
> I think that `UInt.MAX_VALUE` is `-1`, so the current way of validating won't work for unsigned nums.
> 
> I'd prefer refracting the logic to match how KsX JSON does it [#171 (comment)](https://github.com/akuleshov7/ktoml/pull/171#discussion_r1058259095)

Actually the logic should be the same: parsing to the biggest available type and checking bounds: `UInt.MAX_VALUE.toULong() = 4294967295`
